import React, { useState } from 'react'; // JSX component
import { Routes, Route, Link, useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { setSearch, selectFlight, confirmBooking, resetBooking } from './store';

const cities = ['New Delhi', 'Mumbai', 'Bengaluru', 'Kolkata', 'Chennai', 'Hyderabad'];
const flights = [
  { id: 'PX101', airline: 'Phoenix Airlines', code: 'PX 101', from: 'New Delhi', to: 'Mumbai', depart: '07:15', arrive: '09:25', duration: '2h 10m', price: 5499 },
  { id: 'PX214', airline: 'Phoenix Airlines', code: 'PX 214', from: 'New Delhi', to: 'Mumbai', depart: '11:40', arrive: '13:50', duration: '2h 10m', price: 6299 },
  { id: 'PX305', airline: 'Phoenix Airlines', code: 'PX 305', from: 'Mumbai', to: 'New Delhi', depart: '16:30', arrive: '18:40', duration: '2h 10m', price: 5799 }
];

function Layout({ children }) { return <><header><Link to="/">PHOENIX <span>AIRLINES</span></Link><nav><Link to="/flight-search">Book a flight</Link></nav></header>{children}<footer>© 2026 Phoenix Airlines · Fly beyond expectations</footer></>; }
function Home() { const navigate = useNavigate(); return <main className="hero"><div><p className="eyebrow">WELCOME ABOARD</p><h1>Welcome to Flight Booking App</h1><p className="lead">Find your next journey with Phoenix Airlines. Simple bookings, exceptional flights.</p><button className="primary" type="button" onClick={() => navigate('/flight-search')}>SEARCH FLIGHTS HERE <b>→</b></button></div><aside className="hero-card"><p>YOUR NEXT ADVENTURE</p><strong>Fly with confidence</strong><small>Comfort, care, and a little more sky.</small></aside></main>; }
function Search() {
  const dispatch = useDispatch(), navigate = useNavigate(); const saved = useSelector(s => s.flight.search);
  const [form, setForm] = useState(saved), [errors, setErrors] = useState({}), [searched, setSearched] = useState(false);
  const change = e => { const { name, value } = e.target; setForm(x => ({ ...x, [name]: value })); };
  const submit = e => { e.preventDefault(); const next = {}; if (!form.from) next.from = 'Select a departure city'; if (!form.to) next.to = 'Select an arrival city'; if (form.from && form.from === form.to) next.to = 'Departure and arrival cities must be different'; if (!form.departDate) next.departDate = 'Select your departure date'; if (form.tripType === 'round-trip' && !form.returnDate) next.returnDate = 'Select your return date'; setErrors(next); if (!Object.keys(next).length) { dispatch(setSearch(form)); setSearched(true); } };
  const book = flight => { dispatch(selectFlight({ ...flight, from: form.from, to: form.to })); navigate('/flight-booking'); };
  return <main className="page"><div className="title"><p className="eyebrow">PLAN YOUR JOURNEY</p><h2>Search flights</h2><p>Choose where the next chapter begins.</p></div><form className="search-box" onSubmit={submit} noValidate><div className="trip-tabs"><label className={form.tripType === 'one-way' ? 'active' : ''}><input type="radio" name="tripType" value="one-way" checked={form.tripType === 'one-way'} onChange={change}/>One way</label><label className={form.tripType === 'round-trip' ? 'active' : ''}><input type="radio" name="tripType" value="round-trip" checked={form.tripType === 'round-trip'} onChange={change}/>Round trip</label></div><div className="fields"><Field label="From" error={errors.from}><select name="from" value={form.from} onChange={change}><option value="">Departure city</option>{cities.map(c => <option key={c}>{c}</option>)}</select></Field><Field label="To" error={errors.to}><select name="to" value={form.to} onChange={change}><option value="">Arrival city</option>{cities.map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Departure" error={errors.departDate}><input type="date" name="departDate" min={new Date().toISOString().slice(0,10)} value={form.departDate} onChange={change}/></Field>{form.tripType === 'round-trip' && <Field label="Return" error={errors.returnDate}><input type="date" name="returnDate" min={form.departDate || new Date().toISOString().slice(0,10)} value={form.returnDate} onChange={change}/></Field>}<Field label="Travellers"><select name="passengers" value={form.passengers} onChange={change}><option value="1">1 traveller</option><option value="2">2 travellers</option><option value="3">3 travellers</option><option value="4">4 travellers</option></select></Field><button className="primary" type="submit">Search</button></div></form>{searched && <section className="results"><div className="results-head"><h3>Available flights</h3><span>{form.from} → {form.to}</span></div>{flights.map((f, i) => <article className="flight" key={f.id}><div><strong>{f.airline}</strong><small>{f.code} · Economy</small></div><div className="timing"><b>{f.depart}</b><span>{form.from}</span></div><div className="line"><i></i><small>{f.duration}</small></div><div className="timing"><b>{f.arrive}</b><span>{form.to}</span></div><div className="fare"><strong>₹{(f.price * form.passengers).toLocaleString('en-IN')}</strong><small>for {form.passengers} traveller{form.passengers > 1 ? 's' : ''}</small></div><button className="book-flight" type="button" onClick={() => book(f)}>Book flight</button></article>)}</section>}</main>;
}
function Field({ label, error, children }) { return <label className="field"><span>{label}</span>{children}{error && <em role="alert">{error}</em>}</label>; }
function Booking() {
 const navigate = useNavigate(), dispatch = useDispatch(), { selectedFlight, search } = useSelector(s => s.flight); const [form, setForm] = useState({ name: '', email: '', phone: '' }), [errors, setErrors] = useState({});
 if (!selectedFlight) return <main className="page empty"><h2>No flight selected</h2><Link className="primary" to="/flight-search">Search flights</Link></main>;
 const submit = e => { e.preventDefault(); const next = {}; if (!/^[A-Za-z ]{2,}$/.test(form.name.trim())) next.name = 'Enter your full name'; if (!/^\S+@\S+\.\S+$/.test(form.email)) next.email = 'Enter a valid email address'; if (!/^\d{10}$/.test(form.phone.replace(/\s/g, ''))) next.phone = 'Enter a valid 10-digit phone number'; setErrors(next); if (!Object.keys(next).length) { const ref = `PHX${Math.floor(100000 + Math.random()*900000)}`; dispatch(confirmBooking({ ...form, flight: selectedFlight, search, reference: ref })); navigate('/confirmation'); }};
 return <main className="page booking"><div className="title"><p className="eyebrow">ALMOST THERE</p><h2>Traveller details</h2><p>We’ll send your e-ticket to the email address below.</p></div><div className="booking-grid"><form className="details" onSubmit={submit} noValidate><Field label="Full name" error={errors.name}><input type="text" name="name" placeholder="As shown on your ID" value={form.name} onChange={e => setForm({...form, name:e.target.value})}/></Field><Field label="Email address" error={errors.email}><input type="text" name="email" placeholder="you@example.com" value={form.email} onChange={e => setForm({...form, email:e.target.value})}/></Field><Field label="Phone number" error={errors.phone}><input type="text" name="phone" placeholder="10-digit mobile number" value={form.phone} onChange={e => setForm({...form, phone:e.target.value})}/></Field><button className="primary" type="submit">Confirm booking <b>→</b></button></form><FlightCard flight={selectedFlight} search={search}/></div></main>;
}
function FlightCard({flight, search}) { return <aside className="summary"><p className="eyebrow">YOUR FLIGHT</p><h3>{flight.from} <span>→</span> {flight.to}</h3><div className="summary-row"><div><small>DEPARTURE</small><b>{search.departDate || 'Date selected'}</b></div><div><small>FLIGHT</small><b>{flight.code}</b></div></div><hr/><div className="summary-row"><div><small>PASSENGERS</small><b>{search.passengers}</b></div><div><small>TOTAL FARE</small><b>₹{(flight.price * search.passengers).toLocaleString('en-IN')}</b></div></div></aside>; }
function Confirmation() { const booking = useSelector(s => s.flight.booking), dispatch = useDispatch(), navigate = useNavigate(); if (!booking) return <main className="page empty"><h2>Nothing to confirm yet</h2><Link className="primary" to="/">Return home</Link></main>; const home=()=>{dispatch(resetBooking());navigate('/')}; return <main className="page confirm"><div className="success">✓</div><p className="eyebrow">BOOKING CONFIRMED</p><h2>You’re going places, {booking.name.split(' ')[0]}.</h2><p className="lead">Your booking is confirmed. A confirmation has been sent to <b>{booking.email}</b>.</p><section className="ticket"><div className="ticket-top"><span>Phoenix Airlines</span><b>Booking ref: {booking.reference}</b></div><h3>{booking.flight.from} <i>→</i> {booking.flight.to}</h3><div className="ticket-data"><span><small>TRAVELLER</small>{booking.name}</span><span><small>DATE</small>{booking.search.departDate}</span><span><small>FLIGHT</small>{booking.flight.code}</span><span><small>DEPARTS</small>{booking.flight.depart}</span></div></section><button className="primary" onClick={home}>Return to home</button></main>; }
function App() { return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/flight-search" element={<Search/>}/><Route path="/flight-booking" element={<Booking/>}/><Route path="/confirmation" element={<Confirmation/>}/><Route path="*" element={<Home/>}/></Routes></Layout>; }
export default App;
